window.AnupamProducts = [
    {
        id: 'prod-1',
        name: 'Anupam Luxury Blue & Gold Gear Design Side Table Clock',
        title: 'Anupam Luxury Blue & Gold Gear Design Side Table Clock with Lower Shelf Premium Decorative Accent Table',
        image: 'assets/images/prod-1.png',
        alt: 'Anupam luxury blue and gold gear design side table clock with lower shelf',
        images: [
            'assets/images/prod-1.png',
            'assets/images/best-seller-3.png',
            'assets/images/prod-2.png',
            'assets/images/prod-4.png',
            'assets/images/prod-5.png'
        ],
        price: 12115,
        compareAt: 24230,
        rating: 4.8,
        reviews: 214,
        sku: 'ANP-ST-5801',
        type: 'Home & Garden',
        category: 'Clocks',
        brand: 'Anupam',
        inStock: true,
        stockCount: 8,
        featured: true,
        bestselling: true,
        newest: true,
        sold: 186,
        description: 'A statement side table clock with a blue marble-style face, exposed gold gears and a lower storage shelf. Designed as a decorative accent for living rooms, bedrooms and lounge corners.',
        highlights: [
            'Blue and gold gear-inspired clock face',
            'Lower shelf for books, trays or décor',
            'Premium metal finish with glass top',
            'Works as both a timepiece and accent table'
        ]
    },
    {
        id: 'prod-2',
        name: 'Anupam Luxury Blue & Gold Gear Design Coffee Table Clock',
        image: 'assets/images/prod-2.png',
        alt: 'Anupam luxury blue and gold gear design coffee table clock',
        price: 15160,
        compareAt: 30320,
        rating: 4.9,
        reviews: 86,
        category: 'Clocks',
        brand: 'Anupam',
        inStock: true,
        featured: true,
        bestselling: true,
        newest: true,
        sold: 164
    },
    {
        id: 'prod-3',
        name: 'Anupam Luxury Black & Gold Gear Design Wall Clock',
        image: 'assets/images/prod-3.png',
        alt: 'Anupam luxury black and gold gear design wall clock',
        price: 10385,
        compareAt: 20770,
        rating: 4.7,
        reviews: 124,
        category: 'Clocks',
        brand: 'Anupam',
        inStock: true,
        featured: true,
        bestselling: true,
        newest: true,
        sold: 142
    },
    {
        id: 'prod-4',
        name: 'Anupam Luxury Gear Design Coffee Table Clock with Lower Shelf',
        image: 'assets/images/prod-4.png',
        alt: 'Anupam luxury gear design coffee table clock with lower shelf',
        price: 12940,
        compareAt: 25880,
        rating: 4.6,
        reviews: 98,
        category: 'Clocks',
        brand: 'Anupam',
        inStock: true,
        featured: true,
        newest: true,
        sold: 118
    },
    {
        id: 'prod-5',
        name: 'Anupam Luxury Gear Design Table Clock with Roman Numerals',
        image: 'assets/images/prod-5.png',
        alt: 'Anupam luxury gear design table clock with Roman numerals',
        price: 27140,
        compareAt: 54280,
        rating: 4.9,
        reviews: 64,
        category: 'Clocks',
        brand: 'Anupam',
        inStock: true,
        featured: true,
        newest: true,
        sold: 72
    },
    {
        id: 'prod-6',
        name: 'Anupam Premium Lord Ganesha Decorative Idol with Blessing Pose',
        image: 'assets/images/prod-6.png',
        alt: 'Anupam premium Lord Ganesha decorative idol with blessing pose',
        price: 1220,
        compareAt: 1710,
        rating: 4.8,
        reviews: 156,
        category: 'Religious Items',
        brand: 'Anupam',
        inStock: true,
        bestselling: true,
        newest: true,
        sold: 248
    },
    {
        id: 'prod-8',
        name: 'Anupam Premium Buddha in Blessing Hand Decorative Showpiece',
        image: 'assets/images/prod-8-buddha-hand.png',
        alt: 'Anupam premium Buddha in blessing hand decorative showpiece',
        price: 2580,
        compareAt: 3870,
        rating: 4.7,
        reviews: 91,
        category: 'Religious Items',
        brand: 'Anupam',
        inStock: true,
        newest: true,
        sold: 133
    },
    {
        id: 'prod-7',
        name: 'Anupam Antique White & Gold Beverage Dispenser Set',
        image: 'assets/images/prod-7.png',
        alt: 'Anupam antique white and gold beverage dispenser set',
        price: 3125,
        compareAt: 6250,
        rating: 4.6,
        reviews: 77,
        category: 'Drinkware & Serving',
        brand: 'Anupam',
        inStock: true,
        newest: true,
        sold: 95
    },
    {
        id: 'bs-1',
        name: 'Artificial Purple Ranunculus Bunch',
        image: 'assets/images/best-seller-1.png',
        alt: 'Artificial purple ranunculus flower bunch',
        price: 120,
        compareAt: 300,
        rating: 4.8,
        reviews: 214,
        category: 'Artificial Flowers & Plants',
        brand: 'Anupam',
        inStock: true,
        bestselling: true,
        sold: 702
    },
    {
        id: 'bs-2',
        name: 'Luxury Golden Clock Side Table',
        image: 'assets/images/best-seller-2.png',
        alt: 'Gold two-tier clock side table with blue marble face',
        price: 15160,
        compareAt: 30320,
        rating: 4.9,
        reviews: 86,
        category: 'Clocks',
        brand: 'Anupam',
        inStock: true,
        bestselling: true,
        sold: 154
    },
    {
        id: 'bs-3',
        name: 'Blue Marble Clock Coffee Table',
        image: 'assets/images/best-seller-3.png',
        alt: 'Round blue marble clock coffee table with gold rim',
        price: 12115,
        compareAt: 24230,
        rating: 4.7,
        reviews: 124,
        category: 'Clocks',
        brand: 'Anupam',
        inStock: true,
        bestselling: true,
        sold: 139
    },
    {
        id: 'bs-4',
        name: 'Vintage Paris Coffee Wall Clock',
        image: 'assets/images/best-seller-4.png',
        alt: 'Large vintage gold wall clock with Paris coffee motif',
        price: 2470,
        compareAt: 4080,
        rating: 4.6,
        reviews: 98,
        category: 'Clocks',
        brand: 'Hawkins',
        inStock: true,
        sold: 121
    },
    {
        id: 'bs-5',
        name: 'African Queen Decorative Bust',
        image: 'assets/images/best-seller-5.png',
        alt: 'Decorative bust with patterned headwrap, gold hoops and layered necklaces',
        price: 3899,
        compareAt: 5850,
        rating: 5,
        reviews: 64,
        category: 'Decorative Figures',
        brand: 'Anupam',
        inStock: true,
        bestselling: true,
        featured: true,
        sold: 108
    },
    {
        id: 'top-1',
        name: 'African Lady Face Bust',
        image: 'assets/images/top-1.png',
        alt: 'African lady face bust with beaded headwrap and jewellery',
        price: 1210,
        compareAt: 1885,
        rating: 4.5,
        reviews: 72,
        category: 'Decorative Figures',
        brand: 'Anupam',
        inStock: true,
        featured: true,
        sold: 88
    },
    {
        id: 'top-2',
        name: 'Artificial Pink Flower Bunch, Multi Colour',
        image: 'assets/images/top-2.png',
        alt: 'Artificial pink flower bunch',
        price: 120,
        compareAt: 300,
        rating: 4.8,
        reviews: 190,
        category: 'Artificial Flowers & Plants',
        brand: 'Cello',
        inStock: true,
        bestselling: true,
        sold: 640
    },
    {
        id: 'top-4',
        name: 'Anupam Premium Lord Krishna Decorative Showpiece',
        image: 'assets/images/top-4.png',
        alt: 'Anupam premium Lord Krishna decorative showpiece',
        price: 1750,
        compareAt: 2785,
        rating: 4.9,
        reviews: 81,
        category: 'Religious Items',
        brand: 'Anupam',
        inStock: false,
        featured: true,
        sold: 97
    },
    {
        id: 'top-3',
        name: 'Anupam Premium Royal Lion Glass Bowl',
        image: 'assets/images/top-3.png',
        alt: 'Anupam premium royal lion glass bowl',
        price: 6450,
        compareAt: 12900,
        rating: 4.7,
        reviews: 54,
        category: 'Decorative Bowls & Plates',
        brand: 'Borosil',
        inStock: true,
        featured: true,
        sold: 61
    },
    {
        id: 'deal-2',
        name: 'Cream LED Candle Set, Plastic Battery Operated Flameless Candles',
        image: 'assets/images/deal-2.png',
        alt: 'Cream LED candle set with tealights',
        price: 135,
        compareAt: 215,
        rating: 4.4,
        reviews: 214,
        category: 'Flameless Candles',
        brand: 'Milton',
        inStock: true,
        sold: 214
    },
    {
        id: 'deal-3',
        name: 'Assorted Dessert Design Fridge Magnet, Multicolour Plastic Cupcake',
        image: 'assets/images/deal-3.png',
        alt: 'Decorative terracotta vase',
        price: 140,
        compareAt: 380,
        rating: 4.3,
        reviews: 69,
        category: 'Decorative Figures',
        brand: 'Pigeon',
        inStock: true,
        sold: 269
    },
    {
        id: 'deal-1',
        name: 'Artificial Pink Flower Bunch for Vase Arrangement',
        image: 'assets/images/deal-1.png',
        alt: 'Terracotta vase with flowering branches',
        price: 120,
        compareAt: 300,
        rating: 4.6,
        reviews: 148,
        category: 'Vases & Pots',
        brand: 'Prestige',
        inStock: true,
        sold: 318
    },
    {
        id: 'cat-7',
        name: 'Handcrafted Terracotta Decorative Vase',
        image: 'assets/images/cat-7.png',
        alt: 'Handcrafted terracotta decorative vase',
        price: 890,
        compareAt: 1490,
        rating: 4.5,
        reviews: 43,
        category: 'Vases & Pots',
        brand: 'Anupam',
        inStock: true,
        sold: 76
    },
    {
        id: 'cat-4',
        name: 'Warm Ambient Home Lighting Lantern',
        image: 'assets/images/cat-4.png',
        alt: 'Warm ambient home lighting lantern',
        price: 1680,
        compareAt: 2490,
        rating: 4.4,
        reviews: 38,
        category: 'Home Lighting',
        brand: 'Havells',
        inStock: false,
        sold: 52
    },
    {
        id: 'cat-1',
        name: 'Kitchen & Dining Serve Bowl Set',
        image: 'assets/images/cat-1.png',
        alt: 'Kitchen and dining serve bowl set',
        price: 2450,
        compareAt: 3890,
        rating: 4.6,
        reviews: 59,
        category: 'Cookware & Bakeware',
        brand: 'Hawkins',
        inStock: true,
        sold: 84
    },
    {
        id: 'clock-extra',
        name: 'Classic Round Wall Clock with Gold Finish',
        image: 'assets/images/clock.png',
        alt: 'Classic round wall clock with gold finish',
        price: 1990,
        compareAt: 2990,
        rating: 4.5,
        reviews: 47,
        category: 'Clocks',
        brand: 'Bajaj',
        inStock: true,
        sold: 63
    }
];

window.AnupamCatalog = {
    categories: [
        'Artificial Flowers & Plants',
        'Clocks',
        'Decorative Bowls & Plates',
        'Decorative Figures',
        'Flameless Candles',
        'Religious Items',
        'Fountains & Ponds',
        'Cookware & Bakeware',
        'Storage Containers',
        'Drinkware & Serving',
        'Tea Sets',
        'Measuring Cups',
        'Coasters'
    ],
    savings: [
        { id: 'on-sale', label: 'On Sale' },
        { id: 'best-discount', label: 'Best Discount' }
    ],
    availability: [
        { id: 'in-stock', label: 'In Stock' },
        { id: 'out-of-stock', label: 'Out of Stock' }
    ],
    brands() {
        const set = new Set(window.AnupamProducts.map((item) => item.brand).filter(Boolean));
        return Array.from(set).sort();
    },
    priceRange() {
        const prices = window.AnupamProducts.map((item) => item.price);
        return { min: Math.min(...prices), max: Math.max(...prices) };
    },
    byId(id) {
        return window.AnupamProducts.find((item) => item.id === id) || null;
    },
    related(product, limit = 8) {
        const all = window.AnupamProducts;
        const same = all.filter((item) => item.id !== product.id && item.category === product.category);
        const rest = all.filter((item) => item.id !== product.id && item.category !== product.category);
        return same.concat(rest).slice(0, limit);
    },
    gallery(product) {
        if (product.images && product.images.length) return product.images.slice();
        const extras = this.related(product, 5).map((item) => item.image).filter((src) => src !== product.image);
        return [product.image].concat(extras);
    }
};
